### ISSUE TITLE
Missing setting description (adaptive-chunk-gc)

### ISSUE THREAD

**Issue by F1rsi** [TitanVale/Titanium#46]
What is chunk -> adaptive-chunk-gc ?

**Comment by P3ridot** [comment]
#50

**Comment by P3ridot** [comment]
I currently don't have access to code, but when I get home I will answer and describe what it does (and add patch with that)

**Comment by P3ridot** [comment]
But now from scrap of code I have, it's something like normally the value of max loaded chunks before removing them by garbage collector is hardcoded, but this option make this value more flexible - depending on view distance and current player count. If on server is small amount of players we don't have to have a lots chunk loaded, but if amount of players is big preset value could be to small. But I'm not sure yet about all of that.
